#!/system/bin/sh

# @TODO: split actions into individual headphone_plugged, headphone_unplugged scripts tailored to karnak/suez/other
# @TODO: possibly make this a legitimate rc.d service with a pid, start/stop/restart actions

logcat -c; logcat | grep --line-buffered 'QuiescentSpeakerRoute: Processing message CONNECT_WIRED_HEADSET' | while read line; do alsa_amixer cset name='Ext_Speaker_Amp_Switch' 0; alsa_amixer cset name='Ext_Headphone_Amp_Switch' 1; done &
logcat | grep --line-buffered 'QuiescentHeadsetRoute: Processing message DISCONNECT_WIRED_HEADSET' | while read line; do alsa_amixer cset name='Ext_Speaker_Amp_Switch' 1; done &

# -- definite os reported log entries for jack action
# QuiescentSpeakerRoute: Processing message CONNECT_WIRED_HEADSET
# QuiescentHeadsetRoute: Processing message DISCONNECT_WIRED_HEADSET

L="log -p i -t headphonefix"
$L "Initiated 01headphonewatcher background worker.";

